### ISSUE TITLE
Document dependencies (compass, and possibly others?) for `build.py`

### ISSUE THREAD

**Issue by jmandel** [blue-button/bbClear#3]

**Comment by saraswathi55** [comment]
Hello
I work at the Nationwide children's hospital. I thought this will be a nice program to implement which will be even better for small children. I am very eager to make this work. But I am not able to get started. 

I am just trying to compile the sample file. I am getting the following errors.
I am using a windows OS, 64 Bit, Python 2.7. ( it would not compile on python 3.3)
This is the command I give 

$ C:/Python27/python.exe  build.py -f -d data.xml.sample

and I get the following output

Building the project using the 'official' theme...

> Injecting scripts
> Injecting styles
> Traceback (most recent call last):
>   File "build.py", line 388, in <module>
>     build_project(theme=args.theme, watch=args.watch, force=args.force
> e=args.data)
>   File "build.py", line 60, in build_project
>     output = inject_styles(output)
>   File "build.py", line 251, in inject_styles
>     subprocess.call(['compass', 'compile', '-q'])
>   File "c:\Python27\lib\subprocess.py", line 524, in call
>     return Popen(_popenargs, *_kwargs).wait()
>   File "c:\Python27\lib\subprocess.py", line 711, in **init**
>     errread, errwrite)
>   File "c:\Python27\lib\subprocess.py", line 948, in _execute_child
>     startupinfo)
> WindowsError: [Error 2] The system cannot find the file specified

so, I am not sure which file is it asking for ?

> Injecting styles ??  I saw that the lines where the errors were given are the lines which were corrected in github. So, is there a problem in the installation ?    Please help.; Thanks

Saras

**Comment by mjacksonw** [comment]
Hi Saras,

Sorry I hadn't gotten to this documentation bug – you'll need to install [Compass](http://compass-style.org/) and have it (the 'compass' command) in your path when build.py is run.

Let me know if you have any trouble once you have Compass installed: I think that should take care of it.

**Comment by saraswathi55** [comment]
I did install compass ( it asked for Ruby first).> But I am not very
familiar with either of these. I will put it in the path and try to build
it again.

It is a nice software. I  am working with Partners for Kids , an insurance
company  which pays for medicaid/medicare kids in Ohio, for regions around
Columbus. I work with several doctors at my hospital too. One of the
problems, highlighted was that , they want to make sure teenage mothers
come in for checkups or take medicines or vitamins etc. on time. When I saw
the software and the mobile application, I thought this might be  a good
way to give them reminders. They also wanted to have a system where kids
will be brought for regular checkups. Will you be interested in
collaborating with me if I  try to implement his for the kids ?

Saras

Saras

On Sun, Apr 13, 2014 at 9:44 PM, M. Jackson Wilkinson <
notifications@github.com> wrote:

> Hi Saras,
> 
> Sorry I hadn't gotten to this documentation bug – you'll need to install
> Compass http://compass-style.org/ and have it (the 'compass' command)
> in your path when build.py is run.
> 
> Let me know if you have any trouble once you have Compass installed: I
> think that should take care of it.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/blue-button/bbClear/issues/3#issuecomment-40327376
> .

## 

---

Saras Saraswathi PhD
Research Scientist - Data Analyst
Battelle Center for Mathematical Medicine.
The Research Institute at
Nationwide Children’s Hospital,
700 Children's Drive
Columbus, OH 43205

Clinical Instructor,
Department of Pediatrics
The Ohio State University,

---

Motto:  NVRQT
Must have:  a helm to grasp, a course to steer, a port to seek

**Comment by mjacksonw** [comment]
Sure. We use it for children/pediatrics on [Kinsights](https://kinsights.com) as an export tool. jackson@kinsights.com.

**Comment by saraswathi55** [comment]
Hello Jack
I installed compass. I have the path and the directory information and the
error output which is the same as before. Any hints on how to get this done
?

Saras

On Sun, Apr 13, 2014 at 10:15 PM, Saras Saraswathi
saraswathi55@gmail.comwrote:

> I did install compass ( it asked for Ruby first).> But I am not very
> familiar with either of these. I will put it in the path and try to build
> it again.
> 
> It is a nice software. I  am working with Partners for Kids , an insurance
> company  which pays for medicaid/medicare kids in Ohio, for regions around
> Columbus. I work with several doctors at my hospital too. One of the
> problems, highlighted was that , they want to make sure teenage mothers
> come in for checkups or take medicines or vitamins etc. on time. When I saw
> the software and the mobile application, I thought this might be  a good
> way to give them reminders. They also wanted to have a system where kids
> will be brought for regular checkups. Will you be interested in
> collaborating with me if I  try to implement his for the kids ?
> 
> Saras
> 
> Saras
> 
> On Sun, Apr 13, 2014 at 9:44 PM, M. Jackson Wilkinson <
> notifications@github.com> wrote:
> 
> > Hi Saras,
> > 
> > Sorry I hadn't gotten to this documentation bug – you'll need to install
> > Compass http://compass-style.org/ and have it (the 'compass' command)
> > in your path when build.py is run.
> > 
> > Let me know if you have any trouble once you have Compass installed: I
> > think that should take care of it.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/blue-button/bbClear/issues/3#issuecomment-40327376
> > .
> 
> ## 
> 
> ---
> 
> Saras Saraswathi PhD
> Research Scientist - Data Analyst
> Battelle Center for Mathematical Medicine.
> The Research Institute at
> Nationwide Children’s Hospital,
> 700 Children's Drive
> Columbus, OH 43205
> 
> Clinical Instructor,
> Department of Pediatrics
> The Ohio State University,
> 
> ---
> 
> Motto:  NVRQT
> Must have:  a helm to grasp, a course to steer, a port to seek

## 

---

Saras Saraswathi PhD
Research Scientist - Data Analyst
Battelle Center for Mathematical Medicine.
The Research Institute at
Nationwide Children’s Hospital,
700 Children's Drive
Columbus, OH 43205

Clinical Instructor,
Department of Pediatrics
The Ohio State University,

---

Motto:  NVRQT
Must have:  a helm to grasp, a course to steer, a port to seek
 Microsoft Windows [Version 6.1.7601]
 Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

   C:\Users\sxs051\githubcode\bbClear>path
   PATH=  C:\WINDOWS\system32; C:\Program Files\Java\jdk1.7.0_51\bin; C:\Program Fi
   les (x86);\Java\jre;c:\Rtools\bin;c:\Rtools\gcc-4.6.3\bin;C:\Python27;C:\Ruby193
   \bin;  C:\WINDOWS\system32; C:\Program Files\Java\jdk1.7.0_51\bin; C:\Program Fi
   les (x86);\Java\jre;c:\Rtools\bin;c:\Rtools\gcc-4.6.3\bin;C:\Python27;C:\Ruby193
   \bin;

   C:\Users\sxs051\githubcode\bbClear>dir
    Volume in drive C has no label.
    Volume Serial Number is EC43-5631

```
Directory of C:\Users\sxs051\githubcode\bbClear
```

   04/13/2014  07:54 PM    <DIR>          .
   04/13/2014  07:54 PM    <DIR>          ..
   04/13/2014  06:40 PM               356 .gitignore
   04/13/2014  06:40 PM            14,460 build.py
   04/13/2014  06:40 PM               633 CHANGELOG.md
   04/13/2014  07:50 PM    <DIR>          contrib
   04/13/2014  06:40 PM           138,515 data.xml.sample
   04/13/2014  06:40 PM           111,232 data.xml.sample2
   04/13/2014  06:40 PM           282,257 data.xml.sample3
   04/13/2014  06:40 PM             1,809 README.md
   04/13/2014  06:40 PM    <DIR>          themes
                  7 File(s)        549,262 bytes
                  4 Dir(s)  141,278,060,544 bytes free

   C:\Users\sxs051\githubcode\bbClear>dir c:\Ruby193\bin\c*
    Volume in drive C has no label.
    Volume Serial Number is EC43-5631

```
Directory of c:\Ruby193\bin
```

   04/13/2014  10:25 PM               503 compass
   04/13/2014  10:25 PM               156 compass.bat
                  2 File(s)            659 bytes
                0 Dir(s)  141,278,060,544 bytes free

 C:\Users\sxs051>cd C:\Users\sxs051\githubcode\bbClear

 C:\Users\sxs051\githubcode\bbClear> C:/Python27/python.exe  build.py -f -d data.
 xml.sample
 Building the project using the 'official' theme...

> Injecting scripts
> Injecting styles
>  Traceback (most recent call last):
>    File "build.py", line 388, in <module>
>      build_project(theme=args.theme, watch=args.watch, force=args.force, data_fil
>  e=args.data)
>    File "build.py", line 60, in build_project
>      output = inject_styles(output)
>    File "build.py", line 251, in inject_styles
>      subprocess.call(['compass', 'compile', '-q'])
>    File "C:\Python27\lib\subprocess.py", line 524, in call
>      return Popen(_popenargs, *_kwargs).wait()
>    File "C:\Python27\lib\subprocess.py", line 711, in **init**
>      errread, errwrite)
>    File "C:\Python27\lib\subprocess.py", line 948, in _execute_child
>      startupinfo)
>  WindowsError: [Error 2] The system cannot find the file specified

C:\Users\sxs051\githubcode\bbClear>

**Comment by saraswathi55** [comment]
Thanks. I will talk to them and see how it goes.  The hospital is very
possessive about data. So, we need to somehow integrate it with their
system if possible. I have sent the error file.   Looking forward to
working on this.

Saras

On Sun, Apr 13, 2014 at 10:18 PM, M. Jackson Wilkinson <
notifications@github.com> wrote:

> Sure. We use it for children/pediatrics on Kinsightshttps://kinsights.comas an export tool.
> jackson@kinsights.com.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/blue-button/bbClear/issues/3#issuecomment-40328589
> .

## 

---

Saras Saraswathi PhD
Research Scientist - Data Analyst
Battelle Center for Mathematical Medicine.
The Research Institute at
Nationwide Children’s Hospital,
700 Children's Drive
Columbus, OH 43205

Clinical Instructor,
Department of Pediatrics
The Ohio State University,

---

Motto:  NVRQT
Must have:  a helm to grasp, a course to steer, a port to seek

**Comment by mjacksonw** [comment]
@saraswathi55 I don't have access to a Windows machine to test, but as long as 'compass' is runnable from a command prompt without a path (open a prompt and just run 'compass' and make sure it works), it should get past that step.

It works in this way on Linux, OS X, and other POSIX-like environments, but perhaps there need to be adjustments for Windows.

**Comment by saraswathi55** [comment]
Ok..  I forgot to mention that the compass created a project. So it is past
that step. I will see if I can make it work. If you have any ideas besides
this, if not now, but later, Please let me know. Thank you for your input.
I went to your website but I could not see any sample screens. I suppose it
will be the same as given in your sample html file.   I have access to
linux and mac . I will try it on those machines and see. It it works, I
will let you know.

saras

On Mon, Apr 14, 2014 at 12:31 AM, M. Jackson Wilkinson <
notifications@github.com> wrote:

> @saraswathi55 https://github.com/saraswathi55 I don't have access to a
> Windows machine to test, but as long as 'compass' is runnable from a
> command prompt without a path (open a prompt and just run 'compass' and
> make sure it works), it should get past that step.
> 
> It works in this way on Linux, OS X, and other POSIX-like environments,
> but perhaps there need to be adjustments for Windows.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/blue-button/bbClear/issues/3#issuecomment-40332635
> .

## 

---

Saras Saraswathi PhD
Research Scientist - Data Analyst
Battelle Center for Mathematical Medicine.
The Research Institute at
Nationwide Children’s Hospital,
700 Children's Drive
Columbus, OH 43205

Clinical Instructor,
Department of Pediatrics
The Ohio State University,

---

Motto:  NVRQT
Must have:  a helm to grasp, a course to steer, a port to seek
