### ISSUE TITLE
Unicode error when running bbClear

### ISSUE THREAD

**Issue by paniwani** [blue-button/bbClear#5]
I copied the CCDA data from here http://blue-button.github.io/blue-button-for-developers/docs/js/demo.html into 'ccda.xml' and ran:

``` ruby
➜  bbClear git:(master) ✗ python build.py -f -d ccda.xml
Building the project using the 'official' theme...
> Injecting scripts
> Injecting styles
> Injecting data
Traceback (most recent call last):
  File "build.py", line 387, in <module>
    build_project(theme=args.theme, watch=args.watch, force=args.force, data_file=args.data)
  File "build.py", line 60, in build_project
    output = inject_data(input=output, data_file=data_file)
  File "build.py", line 327, in inject_data
    data = '%s<!-- Injected patient data -->\n%s<script style="display: none;" id="xmlBBData" type="text/plain">%s</script>' % (whitespace, whitespace, data)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 73174: ordinal not in range(128)
```

Any advice on overcoming this error?

**Comment by mjacksonw** [comment]
@spencersugarman's pull request (thanks!) should address this issue. Thanks for the heads up!
